<?php

namespace GestionVolBundle\Repository;

/**
 * passagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class passagerRepository extends \Doctrine\ORM\EntityRepository
{
}
