<?php

namespace GestionVolBundle\Repository;

/**
 * volRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class volRepository extends \Doctrine\ORM\EntityRepository
{
}
